version: '3.3'

services:

  backend: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:rw
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000   --reload
    ports:
      - 8000:8000

    environment:
      - DATABASE_HOST = localhost
      - DATABASE_PASSWORD = anselmo
      - DATABASE_NAME = savannah
      - DATABASE_USERNAME = postgres
      - SECRET_KEY = 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM = HS256
  
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=anselmo
      - POSTGRES_DB=savannah
    volumes:
      - postgres-db-v:/var/lib/postgresql/data
volumes:
  postgres-db-v: