"""items tbl

Revision ID: 1fef19b61de2
Revises: 645094e781fd
Create Date: 2023-09-09 13:30:15.187461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fef19b61de2'
down_revision = '645094e781fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'items', ['item_id'], ['item_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'item_id')
    # ### end Alembic commands ###
