"""first commit

Revision ID: 645094e781fd
Revises: 924f054c0039
Create Date: 2023-09-08 23:44:02.475574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645094e781fd'
down_revision = '924f054c0039'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
