"""items tbl

Revision ID: 988dd8cc845b
Revises: 1fef19b61de2
Create Date: 2023-09-09 16:23:11.054558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988dd8cc845b'
down_revision = '1fef19b61de2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
