name: Cloud.Infra.Provisioning

on: push

env:
  AZURE_RESOURCEGROUP_NAME: Savannah.Test
  DOCKER_IMAGE_NAME: savannah.test
  TAG: latest
  DATABASE_HOST: ${{secrets.DATABASE_HOST}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  DATABASE_NAME: ${{secrets.DATABASE_NAME}}
  DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  ALGORITHM: ${{secrets.ALGORITHM}}
  TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
  TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
  URL: https://savannah-api.azurewebsites.net/docs

permissions:
  id-token: write
  contents: read

jobs:
  testing:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    environment:
      name: 'Testing'
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-md
          pip install pytest-emoji
      - name: Run Tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: false
          report-title: 'Test Report'
      - name: Code Coverage Report
        run: |
          coverage run -m pytest
          coverage report 

  deploy_cloud_infrastructure:
    runs-on: ubuntu-latest
    needs: testing
    environment:
      name: 'Cloud'
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
      
      - uses: azure/arm-deploy@v1
        with: 
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./infra.as.code/topology/dev/dev.bicep
          parameters: ./infra.as.code/topology/dev/params.dev.json

  build_and_deploy:
    needs: deploy_cloud_infrastructure
    environment:
      name: 'Production'
      url: ${{env.URL}}
    name: Buld Docker Image and Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.ACR_LOGIN_SERVER}}
          username: ${{secrets.ACR_USER_NAME}}
          password: ${{secrets.ACR_PASSWORD}}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.ACR_LOGIN_SERVER}}/${{env.DOCKER_IMAGE_NAME}}:${{env.TAG}}
          file: Dockerfile 

