name: Cloud.Infra.Provisioning

on: push

env:
  AZURE_RESOURCEGROUP_NAME: Savannah.Test
  DOCKER_IMAGE_NAME: savannah.test
  TAG: latest

permissions:
  id-token: write
  contents: read

jobs:
  deploy_cloud_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
      
      - uses: azure/arm-deploy@v1
        with: 
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./infra.as.code/topology/dev/dev.bicep
          parameters: ./infra.as.code/topology/dev/params.dev.json

  build_and_deploy:
    name: Buld Docker Image and Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.ACR_LOGIN_SERVER}}
          username: ${{secrets.ACR_USER_NAME}}
          password: ${{secrets.ACR_PASSWORD}}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.ACR_LOGIN_SERVER}}/${{env.DOCKER_IMAGE_NAME}}:${{env.TAG}}
          file: Dockerfile 
    
      


